language: julia
julia:
  - 0.5
  - 0.6
notifications:
  email: false
#script: # use the default script setting which is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Shannon")'
after_success:
  - julia -e 'cd(Pkg.dir("Shannon")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
